# CoSpec AI Production Docker Compose with mem0 integration
# Usage: docker compose up

services:
  # PostgreSQL database with pgvector extension for mem0
  mem0-db:
    image: ankane/pgvector:latest
    container_name: mem0-postgres
    environment:
      POSTGRES_DB: mem0
      POSTGRES_USER: mem0user
      POSTGRES_PASSWORD: mem0pass
    volumes:
      - mem0_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  cospec-ai-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cospec-ai-app
    ports:
      - "3000:3000" # 前端端口
      - "3001:3001" # 後端 API 端口
    volumes:
      - ${MARKDOWN_DIR:-./markdown}:/markdown
    environment:
      - MARKDOWN_DIR=/markdown
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.openai.com/v1}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-3.5-turbo}
      - MEM0_API_KEY=${MEM0_API_KEY:-}
      - MEM0_USER_ID=${MEM0_USER_ID:-default-user}
      - MEM0_MODEL=${MEM0_MODEL:-gpt-3.5-turbo}
      - EMBEDDER_MODEL=text-embedding-v4
      - VECTOR_STORE_PROVIDER=pgvector
      - PGVECTOR_HOST=mem0-db
      - PGVECTOR_PORT=5432
      - PGVECTOR_DATABASE=mem0
      - PGVECTOR_USER=mem0user
      - PGVECTOR_PASSWORD=mem0pass
    depends_on:
      - mem0-db
    restart: unless-stopped

volumes:
  mem0_postgres_data:
