version: '3'

services:
  vditor-app:
    build:
      context: .
      dockerfile: Dockerfile.react
    container_name: vditor-app-react-dev
    ports:
      - "3000:3000" # 前端端口
      - "3001:3001" # 後端 API 端口
    volumes:
      - ./app-react:/app # 掛載前端源碼目錄，方便開發
      - /app/node_modules # 匿名卷，防止本地目錄覆蓋容器內的 node_modules
      - ./server:/server # 掛載後端源碼目錄，方便開發
      - /server/node_modules # 匿名卷，防止本地目錄覆蓋容器內的 node_modules
      - ${MARKDOWN_DIR:-./markdown}:/markdown # 掛載 Markdown 文件目錄
    environment:
      - MARKDOWN_DIR=/markdown
      - NODE_ENV=development
    restart: unless-stopped
