# CoSpec AI Production Docker Compose
# Usage: docker compose up

services:
  cospec-ai-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cospec-ai-app
    ports:
      - "3000:3000" # 前端端口
      - "3001:3001" # 後端 API 端口
    volumes:
      - ${MARKDOWN_DIR:-./markdown}:/markdown
    environment:
      - MARKDOWN_DIR=/markdown
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.openai.com/v1}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-3.5-turbo}
    restart: unless-stopped
